server:
  port: ${SERVER_PORT}
spring:
  config:
      import: optional:file:.env[.properties]
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://${DB_HOSTNAME}:${DB_PORT}/${DB_NAME}?currentSchema=${DB_SCHEMA}"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
impulsogov:
  codigoIBGE: ${CODIGO_IBGE}